@extends('admin.layouts.app')
@section('title', $item->exists ? 'Edit Menu Items' : 'Create Menu Items')
@section('page-heading', $item->exists ? 'Edit Menu Items' : 'Create Menu Items')
@section('content')
<form method="POST" action="{{ $item->exists ? route('admin.menu-items.update', $item) : route('admin.menu-items.store') }}" class="card border-0 shadow-sm"><div class="card-body row g-3">@csrf @if($item->exists) @method('PUT') @endif
<div class="col-md-6"><label class="form-label">Label</label><input class="form-control @error('label') is-invalid @enderror" name="label" value="{{ old('label', $item->label) }}">@error('label')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">URL</label><input class="form-control @error('url') is-invalid @enderror" name="url" value="{{ old('url', $item->url) }}">@error('url')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">Sort Order</label><input class="form-control @error('sort_order') is-invalid @enderror" name="sort_order" value="{{ old('sort_order', $item->sort_order) }}">@error('sort_order')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-3"><label class="form-label">Target</label><select class="form-select" name="target"><option value="_self" @selected(old('target',$item->target ?: '_self') === '_self')>Same tab</option><option value="_blank" @selected(old('target',$item->target) === '_blank')>New tab</option></select></div>
<div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><option value="1" @selected(old('status',$item->status ?? true))>Active</option><option value="0" @selected(! old('status',$item->status ?? true))>Inactive</option></select></div>
</div><div class="card-footer bg-white d-flex justify-content-between"><a class="btn btn-outline-secondary" href="{{ route('admin.menu-items.index') }}">Back</a><button class="btn btn-primary-brand">Save</button></div></form>
@endsection
