@extends('admin.layouts.app')
@section('title', $item->exists ? 'Edit Social Links' : 'Create Social Links')
@section('page-heading', $item->exists ? 'Edit Social Links' : 'Create Social Links')
@section('content')
<form method="POST" action="{{ $item->exists ? route('admin.social-links.update', $item) : route('admin.social-links.store') }}" class="card border-0 shadow-sm"><div class="card-body row g-3">@csrf @if($item->exists) @method('PUT') @endif
<div class="col-md-6"><label class="form-label">Platform</label><input class="form-control @error('platform') is-invalid @enderror" name="platform" value="{{ old('platform', $item->platform) }}">@error('platform')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">Icon Class</label><input class="form-control @error('icon_class') is-invalid @enderror" name="icon_class" value="{{ old('icon_class', $item->icon_class) }}">@error('icon_class')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">URL</label><input class="form-control @error('url') is-invalid @enderror" name="url" value="{{ old('url', $item->url) }}">@error('url')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label">Sort Order</label><input class="form-control @error('sort_order') is-invalid @enderror" name="sort_order" value="{{ old('sort_order', $item->sort_order) }}">@error('sort_order')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="status"><option value="1" @selected(old('status',$item->status ?? true))>Active</option><option value="0" @selected(! old('status',$item->status ?? true))>Inactive</option></select></div>
</div><div class="card-footer bg-white d-flex justify-content-between"><a class="btn btn-outline-secondary" href="{{ route('admin.social-links.index') }}">Back</a><button class="btn btn-primary-brand">Save</button></div></form>
@endsection
