@if(($partnerMessagesSection?->status ?? true) && $partnerMessages->isNotEmpty())
<section id="partner-messages" class="partner-messages section-spacing" aria-labelledby="partner-messages-title">
    <div class="container-xl">
        <div class="section-heading text-center mx-auto mb-5"><span class="section-kicker">Leadership Perspectives</span><h2 id="partner-messages-title">{{ $partnerMessagesSection?->title ?: 'Messages from Our Partners' }}</h2><p>{{ $partnerMessagesSection?->subtitle ?: 'Leadership insights, shared values, and the vision behind our journey.' }}</p></div>
        <div class="partner-message-stage" data-partner-carousel data-count="{{ $partnerMessages->count() }}">
            @foreach($partnerMessages as $message)
                <article class="partner-message-card {{ $loop->first ? 'is-active' : '' }}" data-partner-slide aria-hidden="{{ $loop->first ? 'false' : 'true' }}">
                    <div class="partner-message-portrait">@if($message->image_path)<img src="{{ Storage::url($message->image_path) }}" alt="Portrait of {{ $message->name }}" @if(!$loop->first) loading="lazy" @endif>@else<div class="partner-message-placeholder" aria-label="Portrait unavailable"><i class="fa-solid fa-user-tie" aria-hidden="true"></i></div>@endif</div>
                    <div class="partner-message-content"><span class="partner-message-quote" aria-hidden="true">“</span>@if($message->highlighted_text)<p class="partner-message-highlight">{{ $message->highlighted_text }}</p>@endif<p class="partner-message-copy">{{ $message->full_message }}</p><footer class="partner-message-person"><div>@if($message->organization_logo_path)<img src="{{ Storage::url($message->organization_logo_path) }}" alt="{{ $message->organization ? $message->organization.' logo' : 'Organization logo' }}" class="partner-message-logo" loading="lazy">@endif<h3>{{ $message->name }}</h3><p>{{ $message->designation }}@if($message->organization) <span>·</span> {{ $message->organization }}@endif</p></div>@if($message->linkedin_url)<a class="partner-message-linkedin" href="{{ $message->linkedin_url }}" target="_blank" rel="noopener noreferrer" aria-label="View {{ $message->name }} on LinkedIn"><i class="fa-brands fa-linkedin-in" aria-hidden="true"></i></a>@endif</footer></div>
                </article>
            @endforeach
            @if($partnerMessages->count() > 1)<div class="partner-message-controls"><button type="button" class="partner-message-control" data-partner-prev aria-label="Show previous partner message"><i class="fa-solid fa-arrow-left" aria-hidden="true"></i></button><span class="partner-message-indicator" data-partner-indicator aria-live="polite">01 / {{ str_pad((string) $partnerMessages->count(), 2, '0', STR_PAD_LEFT) }}</span><button type="button" class="partner-message-control" data-partner-next aria-label="Show next partner message"><i class="fa-solid fa-arrow-right" aria-hidden="true"></i></button></div><div class="partner-message-tabs" role="tablist" aria-label="Partner messages">@foreach($partnerMessages as $message)<button type="button" class="partner-message-tab {{ $loop->first ? 'is-active' : '' }}" data-partner-tab data-index="{{ $loop->index }}" role="tab" aria-selected="{{ $loop->first ? 'true' : 'false' }}"><span>{{ str_pad((string) ($loop->iteration), 2, '0', STR_PAD_LEFT) }}</span>{{ $message->name }}</button>@endforeach</div>@endif
        </div>
        @if($additionalPartners->isNotEmpty())<div class="partner-message-more mt-5"><h3>More partner perspectives</h3><div class="row g-3">@foreach($additionalPartners as $message)<div class="col-sm-6 col-lg-3"><div class="partner-message-mini">@if($message->image_path)<img src="{{ Storage::url($message->image_path) }}" alt="Portrait of {{ $message->name }}" loading="lazy">@endif<div><strong>{{ $message->name }}</strong><span>{{ $message->designation }}@if($message->organization) · {{ $message->organization }}@endif</span></div></div></div>@endforeach</div></div>@endif
    </div>
</section>
@if($partnerMessages->count() > 1)@push('scripts')<script>
document.querySelectorAll('[data-partner-carousel]').forEach((carousel) => { const slides=[...carousel.querySelectorAll('[data-partner-slide]')], tabs=[...carousel.querySelectorAll('[data-partner-tab]')], indicator=carousel.querySelector('[data-partner-indicator]'); let active=0; const show=(index)=>{active=(index+slides.length)%slides.length; slides.forEach((slide,i)=>{const selected=i===active;slide.classList.toggle('is-active',selected);slide.setAttribute('aria-hidden',String(!selected));});tabs.forEach((tab,i)=>{const selected=i===active;tab.classList.toggle('is-active',selected);tab.setAttribute('aria-selected',String(selected));});if(indicator)indicator.textContent=`${String(active+1).padStart(2,'0')} / ${String(slides.length).padStart(2,'0')}`}; carousel.querySelector('[data-partner-prev]')?.addEventListener('click',()=>show(active-1));carousel.querySelector('[data-partner-next]')?.addEventListener('click',()=>show(active+1));tabs.forEach((tab,i)=>tab.addEventListener('click',()=>show(i)));carousel.addEventListener('keydown',(event)=>{if(event.key==='ArrowLeft')show(active-1);if(event.key==='ArrowRight')show(active+1)});});
</script>
@endpush
@endif
@endif
