
<?php ($companyName = $siteSettings?->company_name ?: config('app.name')); ?>
<?php $__env->startSection('title', 'Projects | '.$companyName); ?>
<?php $__env->startSection('meta_description', 'Browse active construction and engineering projects by '.$companyName.'.'); ?>
<?php $__env->startSection('content'); ?>
<?php echo $__env->make('frontend.partials.page-header', ['title' => 'Projects', 'description' => 'A portfolio of infrastructure, building, power, and development works.'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<section class="container section-spacing">
    <div class="filter-pills mb-5"><a class="btn <?php echo e($activeCategory ? 'btn-outline-secondary' : 'btn-primary-brand'); ?>" href="<?php echo e(route('projects.index')); ?>">All Projects</a><?php $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a class="btn <?php echo e($activeCategory?->is($category) ? 'btn-primary-brand' : 'btn-outline-secondary'); ?>" href="<?php echo e(route('projects.index', ['category' => $category->slug])); ?>"><?php echo e($category->name); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
    <?php if($projects->count()): ?><div class="row g-4"><?php $__currentLoopData = $projects; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $project): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="col-md-6 col-xl-4"><?php echo $__env->make('frontend.partials.content.project-card', ['project' => $project], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><div class="mt-5"><?php echo e($projects->links()); ?></div><?php else: ?> <?php echo $__env->make('frontend.partials.content.empty-state', ['title' => 'No projects found', 'message' => 'Active projects added from the CMS will appear here.'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> <?php endif; ?>
</section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('frontend.layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\APPLICATION\brightcon\resources\views/frontend/pages/projects/index.blade.php ENDPATH**/ ?>