
<?php
    use App\Support\FrontendImage;
    $companyName = $siteSettings?->company_name ?: config('app.name');
    $imageUrl = FrontendImage::url($project->featured_image);
?>
<?php $__env->startSection('title', ($project->seo_title ?: $project->title).' | '.$companyName); ?>
<?php $__env->startSection('meta_description', $project->seo_description ?: ($project->short_description ?: 'Project details from '.$companyName)); ?>
<?php if($imageUrl): ?><?php $__env->startSection('og_image', $imageUrl); ?><?php endif; ?>
<?php $__env->startSection('og_title', ($project->seo_title ?: $project->title).' | '.$companyName); ?>
<?php $__env->startSection('og_description', $project->seo_description ?: ($project->short_description ?: 'Project details from '.$companyName)); ?>
<?php $__env->startSection('content'); ?>
<?php echo $__env->make('frontend.partials.page-header', ['title' => $project->title, 'description' => $project->short_description ?: 'Project details and delivery progress.'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<section class="container section-spacing"><div class="row g-5"><div class="col-lg-8"><div class="detail-media mb-4"><?php if($imageUrl): ?><img src="<?php echo e($imageUrl); ?>" alt="<?php echo e($project->title); ?>" loading="lazy" decoding="async"><?php else: ?><div class="image-placeholder">Project</div><?php endif; ?></div><div class="content-body"><?php echo nl2br(e($project->full_description ?: $project->short_description ?: 'Detailed project information will be updated from the CMS.')); ?></div></div><aside class="col-lg-4"><div class="detail-summary rounded-4 p-4"><span class="card-meta"><?php echo e($project->category?->name ?: 'Project'); ?></span><h2 class="h4">Project Snapshot</h2><div class="progress my-3" role="progressbar" aria-label="Project progress" aria-valuenow="<?php echo e($project->progress_percentage ?? 0); ?>" aria-valuemin="0" aria-valuemax="100"><div class="progress-bar bg-primary-brand" style="width: <?php echo e($project->progress_percentage ?? 0); ?>%"><?php echo e($project->progress_percentage ?? 0); ?>%</div></div><p><?php echo e($project->short_description ?: 'A CMS-managed project record with category, progress, and detailed description.'); ?></p></div><div class="mt-4"><?php echo $__env->make('frontend.partials.content.cta-contact', ['title' => 'Have a similar project?', 'message' => 'Our team can review scope, schedule, and execution requirements.'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></div></aside></div></section>
<?php if($relatedProjects->isNotEmpty()): ?><section class="bg-soft section-spacing"><div class="container"><div class="section-heading mb-4"><span class="section-kicker">More Work</span><h2>Related Projects</h2></div><div class="row g-4"><?php $__currentLoopData = $relatedProjects; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $related): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="col-md-6 col-xl-4"><?php echo $__env->make('frontend.partials.content.project-card', ['project' => $related], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></div></section><?php endif; ?>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('frontend.layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\APPLICATION\brightcon\resources\views/frontend/pages/projects/show.blade.php ENDPATH**/ ?>