
<?php ($companyName = $siteSettings?->company_name ?: config('app.name')); ?>
<?php $__env->startSection('title', 'Contact | '.$companyName); ?>
<?php $__env->startSection('meta_description', 'Contact '.$companyName.' for construction and engineering inquiries.'); ?>
<?php $__env->startSection('content'); ?>
<?php echo $__env->make('frontend.partials.page-header', ['title' => 'Contact Us', 'description' => 'Send project inquiries, requests for quotation, or general messages to our team.'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<section class="container-xl section-spacing"><div class="row g-5"><div class="col-lg-5"><div class="contact-panel rounded-4 p-4 h-100"><h2 class="h4 mb-4">Company Information</h2><?php if($siteSettings?->address): ?><p><strong>Address:</strong><br><?php echo e($siteSettings->address); ?></p><?php endif; ?> <?php if($siteSettings?->phone): ?><p><strong>Phone:</strong><br><a href="tel:<?php echo e($siteSettings->phone); ?>"><?php echo e($siteSettings->phone); ?></a></p><?php endif; ?> <?php if($siteSettings?->email): ?><p><strong>Email:</strong><br><a href="mailto:<?php echo e($siteSettings->email); ?>"><?php echo e($siteSettings->email); ?></a></p><?php endif; ?> <?php if($socialLinks->isNotEmpty()): ?><div class="d-flex gap-3 flex-wrap mt-4"><?php $__currentLoopData = $socialLinks; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $social): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php if(blank($social->url)) continue; ?><a href="<?php echo e($social->url); ?>" target="_blank" rel="noopener" class="social-pill" aria-label="<?php echo e($social->platform); ?>"><?php echo e($social->platform); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><?php endif; ?><div class="map-placeholder mt-4">Map or embedded location can be connected from future CMS settings.</div></div></div><div class="col-lg-7"><div class="contact-panel rounded-4 p-4 p-lg-5"><?php if(session('success')): ?><div class="alert alert-success"><?php echo e(session('success')); ?></div><?php endif; ?><h2 class="h4 mb-4">Send a Message</h2><?php echo $__env->make('frontend.partials.contact-form', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?></div></div></div></section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('frontend.layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\APPLICATION\brightcon\resources\views/frontend/pages/contact.blade.php ENDPATH**/ ?>