
<?php $__env->startSection('title', 'Dashboard'); ?>
<?php $__env->startSection('page-heading', 'Dashboard'); ?>
<?php $__env->startSection('content'); ?>
<div class="row g-4">
 <?php $__currentLoopData = [['Total Projects',$totalProjects],['Active Projects',$activeProjects],['Featured Projects',$featuredProjects],['Total Services',$totalServices],['Active Services',$activeServices],['Gallery Images',$totalGalleryImages],['Active Gallery Images',$activeGalleryImages],['Contact Messages',$totalContactMessages],['Unread Messages',$unreadContactMessages]]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$label,$value]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
 <div class="col-md-6 col-xl"><div class="card stat-card border-0 shadow-sm h-100"><div class="card-body"><div class="text-muted small"><?php echo e($label); ?></div><div class="display-6 fw-bold"><?php echo e($value ?? 0); ?></div></div></div></div>
 <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
 <div class="col-lg-7"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Recent Contact Messages</div><div class="card-body p-0"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Name</th><th>Email</th><th>Subject</th><th>Status</th></tr></thead><tbody><?php $__empty_1 = true; $__currentLoopData = $recentContactMessages; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $message): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?><tr><td><?php echo e($message->full_name); ?></td><td><?php echo e($message->email); ?></td><td><?php echo e($message->subject ?? '—'); ?></td><td><span class="badge <?php echo e($message->is_read ? 'text-bg-secondary' : 'text-bg-danger'); ?>"><?php echo e($message->is_read ? 'Read' : 'Unread'); ?></span></td></tr><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?><tr><td colspan="4" class="text-center text-muted py-4">No contact messages yet.</td></tr><?php endif; ?></tbody></table></div></div></div></div>
 <div class="col-lg-5"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Quick Links</div><div class="card-body d-grid gap-2"><?php $__currentLoopData = [['General Settings',route('admin.settings.general.edit')],['Theme Settings',route('admin.settings.theme.edit')],['Menu Items',route('admin.menu-items.index')],['Social Links',route('admin.social-links.index')],['Footer Links',route('admin.footer-links.index')],['Projects',route('admin.projects.index')],['Services',route('admin.services.index')],['Gallery Images',route('admin.gallery-images.index')]]; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as [$label,$url]): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a class="btn btn-outline-primary-brand text-start" href="<?php echo e($url); ?>"><?php echo e($label); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></div></div>
</div>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('admin.layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\APPLICATION\brightcon\resources\views/admin/pages/dashboard.blade.php ENDPATH**/ ?>