
<?php ($companyName = $siteSettings?->company_name ?: config('app.name')); ?>
<?php $__env->startSection('title', 'About | '.$companyName); ?>
<?php $__env->startSection('meta_description', $aboutSection?->content ?: 'Learn about our construction and engineering company.'); ?>
<?php $__env->startSection('content'); ?>
<?php echo $__env->make('frontend.partials.page-header', ['title' => 'About Us', 'description' => $aboutSection?->subtitle ?: 'Reliable engineering and construction delivery with safety, quality, and accountability.'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<section id="overview" class="container-xl section-spacing"><div class="row g-5 align-items-center"><div class="col-lg-7"><span class="section-kicker">Company Profile</span><h2><?php echo e($aboutSection?->title ?: 'Building resilient infrastructure for tomorrow'); ?></h2><p class="section-copy"><?php echo e($aboutSection?->content ?: 'We plan, build, and deliver civil, structural, building, road, and power-sector projects for public and private clients. Our teams combine disciplined project management with field-tested construction expertise.'); ?></p></div><div class="col-lg-5"><div class="stats-grid"> <div><strong><?php echo e($activeProjectsCount); ?></strong><span>Completed Projects</span></div><div><strong><?php echo e($activeServicesCount); ?></strong><span>Services</span></div><div><strong>10+</strong><span>Years Experience</span></div><div><strong>50+</strong><span>Skilled Team</span></div></div></div></div></section>
<section id="mission-vision" class="bg-soft section-spacing"><div class="container-xl"><div class="row g-4"><div class="col-md-6"><div class="info-card h-100"><h2 class="h4">Our Mission</h2><p>To deliver safe, durable, and cost-effective construction solutions through accountable management, skilled teams, and dependable engineering practices.</p></div></div><div class="col-md-6"><div class="info-card h-100"><h2 class="h4">Our Vision</h2><p>To be a trusted construction partner recognized for quality workmanship, timely delivery, responsible growth, and long-term client relationships.</p></div></div></div></div></section>
<section class="container-xl section-spacing"><div class="section-heading text-center mx-auto mb-5"><span class="section-kicker">Why Choose Us</span><h2>Built around quality, safety, and delivery</h2></div><div class="row g-4"><?php $__currentLoopData = ['Experienced project teams','Safety-first site execution','Quality-focused workmanship','Transparent communication']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $item): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><div class="col-md-6 col-xl-3"><div class="info-card h-100"><h3 class="h5"><?php echo e($item); ?></h3><p class="mb-0">Professional systems and practical field experience keep projects moving with confidence.</p></div></div><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div></section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('frontend.layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\APPLICATION\brightcon\resources\views/frontend/pages/about.blade.php ENDPATH**/ ?>