
<?php use App\Support\FrontendImage; ?>
<?php ($companyName = $siteSettings?->company_name ?: config('app.name')); ?>
<?php $__env->startSection('title', 'Gallery | '.$companyName); ?>
<?php $__env->startSection('meta_description', 'Browse construction site, project, and equipment gallery images.'); ?>
<?php $__env->startSection('content'); ?>
<?php echo $__env->make('frontend.partials.page-header', ['title' => 'Gallery', 'description' => 'Project snapshots, site progress, equipment, and completed work highlights.'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?>
<section class="container-xl section-spacing">
    <div class="filter-pills mb-5"><a class="btn <?php echo e($activeCategory ? 'btn-outline-secondary' : 'btn-primary-brand'); ?>" href="<?php echo e(route('gallery.index')); ?>">All Images</a><?php $__currentLoopData = $categories; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $category): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><a class="btn <?php echo e($activeCategory === $category ? 'btn-primary-brand' : 'btn-outline-secondary'); ?>" href="<?php echo e(route('gallery.index', ['category' => $category])); ?>"><?php echo e($category); ?></a><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div>
    <?php if($images->count()): ?><div class="gallery-grid"><?php $__currentLoopData = $images; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $image): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?><?php ($imageUrl = FrontendImage::url($image->image)); ?><figure class="gallery-card"><?php if($imageUrl): ?><img src="<?php echo e($imageUrl); ?>" alt="<?php echo e($image->title ?: $image->category ?: 'Gallery image'); ?>" loading="lazy" decoding="async"><?php else: ?><div class="image-placeholder">Gallery</div><?php endif; ?><figcaption><strong><?php echo e($image->title ?: 'Project Image'); ?></strong><span><?php echo e($image->category ?: 'Gallery'); ?></span></figcaption></figure><?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?></div><div class="mt-5"><?php echo e($images->links()); ?></div><?php else: ?> <?php echo $__env->make('frontend.partials.content.empty-state', ['title' => 'No gallery images found', 'message' => 'Active gallery images added from the CMS will appear here.'], array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?> <?php endif; ?>
</section>
<?php $__env->stopSection(); ?>

<?php echo $__env->make('frontend.layouts.app', array_diff_key(get_defined_vars(), ['__data' => 1, '__path' => 1]))->render(); ?><?php /**PATH D:\APPLICATION\brightcon\resources\views/frontend/pages/gallery/index.blade.php ENDPATH**/ ?>