<?php

return [
    'product_version' => env('CMS_PRODUCT_VERSION', '1.0.0'),
    'defaults' => [
        'company_name' => 'BrightCon',
        'tagline' => 'Construction & Engineering',
        'logo' => null,
        'favicon' => null,
        'primary_color' => '#d80d4c',
        'secondary_color' => '#ffffff',
        'footer_background_color' => '#111827',
        'body_text_color' => '#374151',
        'heading_text_color' => '#111827',
        'body_font_family' => 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        'heading_font_family' => 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
        'base_font_size' => '16px',
        'h1_font_size' => '2.5rem',
        'h2_font_size' => '2rem',
        'h3_font_size' => '1.5rem',
        'button_radius' => '.375rem',
        'section_spacing' => '4rem',
        'show_contact_map' => false,
        'map_zoom' => 15,
        'default_language' => 'en',
        'timezone' => 'Asia/Dhaka',
        'date_format' => 'M d, Y',
        'website_status' => 'active',
        'show_powered_by' => true,
        'contact_form_enabled' => true,
        'contact_phone_enabled' => true,
        'contact_subject_enabled' => true,
        'organization_schema_enabled' => false,
        'custom_css_enabled' => false,
        'robots_directive' => 'index, follow',
    ],
    'cache' => [
        'site' => 'cms.site_settings',
        'theme' => 'cms.theme_settings',
        'social' => 'cms.social_links',
        'header' => 'cms.header_menu',
        'footer' => 'cms.footer_links',
        'frontend' => 'cms.frontend_context',
        'seo' => 'cms.seo_context',
        'legacy' => [
            'site_settings', 'theme_settings', 'social_links_active_ordered',
            'menu_items_active_ordered', 'footer_links_active_ordered',
        ],
    ],
];
