<?php

return [
    'product_name' => 'Buildora CMS',
    'product_slug' => 'buildora-cms',
    'version_source' => 'CMS_VERSION',
    'default_version' => '1.0.0',
    'output_directory' => 'release',
    'checksum_algorithm' => 'sha256',
    'manifest_format' => 'json',
    'approval_states' => ['internal_test', 'release_candidate', 'commercially_approved'],
    'license' => ['required_for_commercial' => true, 'final_file' => 'LICENSE', 'draft_file' => 'LICENSE-DRAFT.md'],
    'variants' => [
        'source' => ['vendor' => false, 'public_build' => true, 'tests' => false],
        'shared_hosting' => ['vendor' => true, 'public_build' => true, 'tests' => false],
        'documentation' => ['vendor' => false, 'public_build' => false, 'tests' => false],
    ],
    'source_roots' => ['app', 'bootstrap', 'config', 'database', 'public', 'resources', 'routes', 'storage', 'tests'],
    'source_files' => ['artisan', '.env.example', 'README.md', 'CHANGELOG.md', 'LICENSE', 'LICENSE-DRAFT.md', 'THIRD-PARTY-LICENSES.md', 'composer.json', 'composer.lock', 'package.json', 'package-lock.json', 'phpunit.xml', 'vite.config.js'],
    'required_files' => ['.env.example', 'artisan', 'composer.json', 'composer.lock', 'README.md', 'CHANGELOG.md', 'LICENSE', 'THIRD-PARTY-LICENSES.md'],
    'excluded_paths' => ['.git', '.github', '.env', 'node_modules', 'vendor', 'release', 'public/favicon.ico', 'public/storage', 'storage/app/public/uploads', 'storage/logs', 'storage/framework/cache', 'storage/framework/sessions', 'storage/framework/testing', 'storage/framework/views', 'bootstrap/cache'],
    'excluded_extensions' => ['log', 'sql', 'sqlite', 'sqlite3', 'db', 'dump', 'bak', 'backup', 'zip', 'tar', 'gz', 'tgz', 'pem', 'key', 'p12', 'pfx', 'map'],
    'excluded_directories' => ['.git', 'vendor', 'node_modules', 'release', 'storage/framework', 'storage/logs', 'bootstrap/cache'],
    'blocking_extensions' => ['log', 'sql', 'sqlite', 'sqlite3', 'db', 'dump', 'bak', 'backup', 'zip', 'tar', 'gz', 'tgz', 'pem', 'key', 'p12', 'pfx'],
    'excluded_content_files' => ['composer.lock', 'package-lock.json'],
    'branding_excluded_files' => ['config/commercial_release.php', 'app/Services/Release/ReleaseScanner.php', 'tests/Feature/CommercialReleaseAuditCommandTest.php', 'documentation/commercial-readiness-audit.md', 'documentation/phase-b-settings-audit.md', 'documentation/phase-c-branding-audit.md', 'documentation/audits/phase-g-pre-change-release-audit.md'],
    'forbidden_branding' => [['term' => 'BrightCon', 'severity' => 'fail'], ['term' => 'Bright Construction', 'severity' => 'fail'], ['term' => 'brightconeng.com', 'severity' => 'fail']],
    'sensitive_content_rules' => [
        'credential assignment' => '/\b(?:password|secret|api[_-]?key|access[_-]?token|private[_-]?key)\s*[:=]\s*[\'\"][^\'\"]{4,}/i',
        'authorization token' => '/\b(?:authorization|bearer)\s*[:= ]\s*[\'\"]?[^\s\'\"]{8,}/i',
        'default credential' => '/\b(?:password|secret)\s*[:=]\s*[\'\"]?(?:admin|password|changeme|secret|12345678)\b/i',
    ],
    'production_domain_rules' => ['/https?:\/\/(?!example\.(?:com|org|net))[^\s\'\"]+/i'],
    'absolute_path_rules' => ['/(?:\/home\/|\/var\/www\/|[A-Z]:\\\\Users\\\\)[^\s\'\"]+/i'],
    'unverified_assets' => ['public/favicon.ico', 'public/storage/uploads', 'storage/app/public/uploads'],
    'allowed_runtime_placeholders' => ['bootstrap/cache/.gitignore', 'storage/framework/cache/.gitignore', 'storage/framework/cache/data/.gitignore', 'storage/framework/sessions/.gitignore', 'storage/framework/testing/.gitignore', 'storage/framework/views/.gitignore', 'storage/logs/.gitignore'],
    'buyer_documentation' => [
        'README.md', 'CHANGELOG.md', 'LICENSE', 'LICENSE-DRAFT.md', 'THIRD-PARTY-LICENSES.md',
        'documentation/read-me-first.md', 'documentation/installation-guide.md', 'documentation/shared-hosting-installation.md',
        'documentation/cli-installation.md', 'docs/admin-user-manual.md', 'documentation/configuration-guide.md',
        'documentation/offline-license-activation.md', 'documentation/demo-mode.md', 'documentation/update-policy.md',
        'documentation/backup-and-recovery.md', 'documentation/installation-recovery.md', 'documentation/server-requirements.md',
        'documentation/security-recommendations.md', 'documentation/support-policy-template.md', 'documentation/refund-policy-template.md',
    ],
    'asset_provenance' => [
        'approved' => ['public/build'],
        'required_notices' => ['THIRD-PARTY-LICENSES.md'],
        'unverified' => ['public/favicon.ico', 'public/storage', 'storage/app/public/uploads'],
    ],
    'packaging' => [
        'vendor' => 'CONDITIONAL: shared-hosting only; isolated Composer --no-dev build; owner/legal redistribution approval remains required.',
        'public_build' => 'INCLUDE: source and shared-hosting packages include the verified generated build and third-party notices.',
    ],
    'operational_license_providers' => ['offline'],
    'supported_license_providers' => ['offline'],
    'acceptance_reports' => ['mysql' => 'documentation/acceptance/mysql.json', 'fresh_zip' => 'documentation/acceptance/fresh-zip.json'],
];
