<?php

return [
    'product_name' => 'Buildora CMS',
    'product_slug' => 'buildora-cms',
    'licensor' => 'Naxas Limited',
    'license_type' => 'proprietary',
    'license_identity' => [
        'status' => 'OWNER-APPROVED FINAL LICENSE',
        'licensor' => 'Naxas Limited',
        'address' => 'House # 04 (7th Floor), Main Road, Block F, Banasree, Rampura, Dhaka-1219, Bangladesh',
        'contact' => 'info.naxasltd@gmail.com',
        'governing_law' => 'The laws of the People’s Republic of Bangladesh',
        'jurisdiction' => 'The competent courts of Dhaka, Bangladesh shall have exclusive jurisdiction.',
        'effective_date' => '27 July 2026',
        'signatory' => 'Dipak Chakraborty',
        'approval_date' => '27 July 2026',
    ],
    'version_source' => 'CMS_VERSION',
    'default_version' => '1.0.0',
    'output_directory' => 'release',
    'checksum_algorithm' => 'sha256',
    'manifest_format' => 'json',
    'approval_states' => ['internal_test', 'release_candidate', 'commercially_approved'],
    'license' => ['required_for_commercial' => true, 'final_file' => 'LICENSE', 'draft_file' => 'LICENSE-DRAFT.md'],
    'variants' => [
        'source' => ['vendor' => false, 'public_build' => true, 'tests' => false],
        'shared_hosting' => ['vendor' => true, 'public_build' => true, 'tests' => false],
        'documentation' => ['vendor' => false, 'public_build' => false, 'tests' => false],
    ],
    'source_roots' => ['app', 'bootstrap', 'config', 'database', 'public', 'resources', 'routes', 'storage', 'tests'],
    'source_files' => ['artisan', '.env.example', 'README.md', 'CHANGELOG.md', 'LICENSE', 'THIRD-PARTY-LICENSES.md', 'composer.json', 'composer.lock', 'package.json', 'package-lock.json', 'phpunit.xml', 'vite.config.js'],
    'required_files' => ['.env.example', 'artisan', 'composer.json', 'composer.lock', 'README.md', 'CHANGELOG.md', 'LICENSE', 'THIRD-PARTY-LICENSES.md'],
    'excluded_paths' => ['.git', '.github', '.env', 'node_modules', 'vendor', 'release', 'public/favicon.ico', 'public/storage', 'storage/app/public/uploads', 'storage/logs', 'storage/framework/cache', 'storage/framework/sessions', 'storage/framework/testing', 'storage/framework/views', 'bootstrap/cache'],
    'excluded_extensions' => ['log', 'sql', 'sqlite', 'sqlite3', 'db', 'dump', 'bak', 'backup', 'zip', 'tar', 'gz', 'tgz', 'pem', 'key', 'p12', 'pfx', 'map'],
    'excluded_directories' => ['.git', 'vendor', 'node_modules', 'release', 'storage/framework', 'storage/logs', 'bootstrap/cache'],
    'blocking_extensions' => ['log', 'sql', 'sqlite', 'sqlite3', 'db', 'dump', 'bak', 'backup', 'zip', 'tar', 'gz', 'tgz', 'pem', 'key', 'p12', 'pfx'],
    'excluded_content_files' => ['composer.lock', 'package-lock.json'],
    'branding_excluded_files' => ['config/commercial_release.php', 'app/Services/Release/ReleaseScanner.php', 'tests/Feature/CommercialReleaseAuditCommandTest.php', 'documentation/commercial-readiness-audit.md', 'documentation/phase-b-settings-audit.md', 'documentation/phase-c-branding-audit.md', 'documentation/audits/phase-g-pre-change-release-audit.md'],
    'forbidden_branding' => [['term' => 'BrightCon', 'severity' => 'fail'], ['term' => 'Bright Construction', 'severity' => 'fail'], ['term' => 'brightconeng.com', 'severity' => 'fail']],
    'sensitive_content_rules' => [
        'credential assignment' => '/\b(?:password|secret|api[_-]?key|access[_-]?token|private[_-]?key)\s*[:=]\s*[\'\"][^\'\"]{4,}/i',
        'authorization token' => '/\b(?:authorization|bearer)\s*[:= ]\s*[\'\"]?[^\s\'\"]{8,}/i',
        'default credential' => '/\b(?:password|secret)\s*[:=]\s*[\'\"]?(?:admin|password|changeme|secret|12345678)\b/i',
    ],
    'production_domain_rules' => ['/https?:\/\/(?!example\.(?:com|org|net))[^\s\'\"]+/i'],
    'absolute_path_rules' => ['/(?:\/home\/|\/var\/www\/|[A-Z]:\\\\Users\\\\)[^\s\'\"]+/i'],
    'unverified_assets' => ['public/favicon.ico', 'public/storage/uploads', 'storage/app/public/uploads'],
    'allowed_runtime_placeholders' => ['bootstrap/cache/.gitignore', 'storage/framework/cache/.gitignore', 'storage/framework/cache/data/.gitignore', 'storage/framework/sessions/.gitignore', 'storage/framework/testing/.gitignore', 'storage/framework/views/.gitignore', 'storage/logs/.gitignore'],
    'buyer_documentation' => [
        'README.md', 'CHANGELOG.md', 'LICENSE', 'THIRD-PARTY-LICENSES.md',
        'documentation/read-me-first.md', 'documentation/installation-guide.md', 'documentation/shared-hosting-installation.md',
        'documentation/cli-installation.md', 'docs/admin-user-manual.md', 'documentation/configuration-guide.md',
        'documentation/offline-license-activation.md', 'documentation/demo-mode.md', 'documentation/update-policy.md',
        'documentation/custom-pages-guide.md', 'documentation/menu-management-guide.md', 'documentation/equipment-management-guide.md',
        'documentation/competency-management-guide.md', 'documentation/contact-message-guide.md', 'documentation/contact-email-configuration.md',
        'documentation/leadership-or-partner-message-guide.md', 'documentation/testimonials-guide.md',
        'documentation/backup-and-recovery.md', 'documentation/installation-recovery.md', 'documentation/server-requirements.md',
        'documentation/security-recommendations.md', 'documentation/support-policy-template.md', 'documentation/refund-policy-template.md',
        'documentation/single-site-license.md', 'documentation/white-label-policy.md', 'documentation/support-policy.md',
        'documentation/refund-policy.md', 'documentation/client-handover-policy.md', 'documentation/no-saas-policy.md',
        'documentation/license-activation.md',
    ],
    'asset_provenance' => [
        'approved' => ['public/build'],
        'required_notices' => ['THIRD-PARTY-LICENSES.md'],
        'unverified' => ['public/favicon.ico', 'public/storage', 'storage/app/public/uploads'],
    ],
    'packaging' => [
        'vendor' => 'CONDITIONAL: shared-hosting only; isolated Composer --no-dev build; owner/legal redistribution approval remains required.',
        'public_build' => 'INCLUDE: source and shared-hosting packages include the verified generated build and third-party notices.',
    ],
    'operational_license_providers' => ['offline'],
    'supported_license_providers' => ['offline'],
    'acceptance_reports' => [
        'mysql' => ['path' => 'documentation/acceptance/mysql.json', 'required' => ['schema_version', 'status', 'tested_at', 'database_product', 'database_version', 'scenarios']],
        'fresh_zip' => ['path' => 'documentation/acceptance/fresh-zip.json', 'required' => ['schema_version', 'status', 'tested_at', 'archive_sha256', 'package_variant', 'inventory_verified']],
        'asset_provenance' => ['path' => 'documentation/acceptance/asset-provenance.json', 'required' => ['schema_version', 'status', 'assets', 'owner_approved']],
        'vendor_redistribution' => ['path' => 'documentation/acceptance/vendor-redistribution.json', 'required' => ['schema_version', 'status', 'shared_hosting_enabled', 'dependencies', 'owner_approved']],
        'smtp' => ['path' => 'documentation/acceptance/smtp.json', 'required' => ['schema_version', 'status', 'sandbox', 'submission', 'reply', 'failure_handling']],
        'browser' => ['path' => 'documentation/acceptance/browser.json', 'required' => ['schema_version', 'status', 'browser', 'widths', 'screenshots']],
        'accessibility' => ['path' => 'documentation/acceptance/accessibility.json', 'required' => ['schema_version', 'status', 'tested_at', 'tools', 'checks']],
        'upgrade' => ['path' => 'documentation/acceptance/upgrade.json', 'required' => ['schema_version', 'status', 'tested_at', 'baseline', 'checks']],
        'security' => ['path' => 'documentation/acceptance/security.json', 'required' => ['schema_version', 'status', 'tested_at', 'source_scan', 'package_scans']],
        'final_report' => ['path' => 'documentation/acceptance/final-commercial-acceptance.json', 'required' => ['schema_version', 'decision', 'product_version', 'source_commit', 'gates'], 'status_field' => 'decision'],
    ],
];
