@extends('admin.layouts.app')
@section('title', $item->exists ? 'Edit Partner Message' : 'Create Partner Message')
@section('page-heading', $item->exists ? 'Edit Partner Message' : 'Create Partner Message')
@section('content')
<form method="POST" action="{{ $item->exists ? route('admin.partner-messages.update', $item) : route('admin.partner-messages.store') }}" enctype="multipart/form-data" class="card border-0 shadow-sm">@csrf @if($item->exists) @method('PUT') @endif
<div class="card-body row g-3">
@foreach(['name' => 'Name *', 'designation' => 'Designation *', 'organization' => 'Organization', 'linkedin_url' => 'LinkedIn URL', 'display_order' => 'Display Order'] as $field => $label)<div class="col-md-6"><label class="form-label" for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" class="form-control @error($field) is-invalid @enderror" name="{{ $field }}" value="{{ old($field, $item->$field) }}">@error($field)<div class="invalid-feedback">{{ $message }}</div>@enderror</div>@endforeach
<div class="col-md-6"><label class="form-label" for="published_at">Publish date</label><input id="published_at" type="datetime-local" class="form-control @error('published_at') is-invalid @enderror" name="published_at" value="{{ old('published_at', $item->published_at?->format('Y-m-d\\TH:i')) }}"><div class="form-text">Leave blank to keep this message out of the public About page.</div>@error('published_at')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-12"><label class="form-label" for="highlighted_text">Highlighted statement</label><textarea id="highlighted_text" class="form-control @error('highlighted_text') is-invalid @enderror" name="highlighted_text" rows="2">{{ old('highlighted_text', $item->highlighted_text) }}</textarea>@error('highlighted_text')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="col-md-6"><label class="form-label" for="short_message">Short message</label><textarea id="short_message" class="form-control @error('short_message') is-invalid @enderror" name="short_message" rows="3">{{ old('short_message', $item->short_message) }}</textarea>@error('short_message')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6"><label class="form-label" for="full_message">Full message *</label><textarea id="full_message" class="form-control @error('full_message') is-invalid @enderror" name="full_message" rows="6" required>{{ old('full_message', $item->full_message) }}</textarea><div class="form-text">Plain text only; paragraph breaks are preserved publicly.</div>@error('full_message')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
@foreach(['image_path' => ['Portrait', 'Professional portrait, JPEG, PNG, or WebP; up to 4 MB.'], 'organization_logo_path' => ['Organization logo', 'JPEG, PNG, or WebP; up to 2 MB.']] as $field => [$label, $help])<div class="col-md-6"><label class="form-label" for="{{ $field }}">{{ $label }}</label><input id="{{ $field }}" type="file" class="form-control @error($field) is-invalid @enderror" name="{{ $field }}" accept="image/jpeg,image/png,image/webp"><div class="form-text">{{ $help }}</div>@error($field)<div class="invalid-feedback">{{ $message }}</div>@enderror @if($item->$field)<img src="{{ Storage::url($item->$field) }}" class="img-thumbnail mt-2" style="max-height:120px" alt="Current {{ strtolower($label) }}">@endif</div>@endforeach
<div class="col-md-3"><label class="form-label">Status</label><select class="form-select" name="is_active"><option value="1" @selected(old('is_active', $item->is_active ?? true))>Active</option><option value="0" @selected(!old('is_active', $item->is_active ?? true))>Inactive</option></select></div><div class="col-md-3"><label class="form-label">Featured</label><select class="form-select" name="is_featured"><option value="0" @selected(!old('is_featured', $item->is_featured ?? false))>No</option><option value="1" @selected(old('is_featured', $item->is_featured ?? false))>Yes</option></select></div>
</div><div class="card-footer bg-white d-flex justify-content-between"><a class="btn btn-outline-secondary" href="{{ route('admin.partner-messages.index') }}">Back</a><button class="btn btn-primary-brand">Save</button></div></form>
@endsection
