@extends('admin.layouts.app')
@section('title', 'Partner Messages')
@section('page-heading', 'Partner Messages')
@section('content')
<div class="card border-0 shadow-sm">
    <div class="card-header bg-white d-flex flex-wrap gap-3 justify-content-between align-items-center"><strong>Partner Messages</strong><a class="btn btn-primary-brand btn-sm" href="{{ route('admin.partner-messages.create') }}">Add Partner Message</a></div>
    <div class="card-body border-bottom"><form class="row g-2"><div class="col-md-6"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Search name, designation, or organization"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">All statuses</option><option value="1" @selected(request('status') === '1')>Active</option><option value="0" @selected(request('status') === '0')>Inactive</option></select></div><div class="col-md-3"><button class="btn btn-outline-primary-brand">Filter</button><a class="btn btn-link" href="{{ route('admin.partner-messages.index') }}">Reset</a></div></form></div>
    <div class="card-body p-0"><div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Partner</th><th>Organization</th><th>Order</th><th>Published</th><th>Status</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse($items as $item)<tr><td><div class="d-flex gap-2 align-items-center">@if($item->image_path)<img src="{{ Storage::url($item->image_path) }}" alt="" class="rounded-circle" style="height:42px;width:42px;object-fit:cover">@endif<div><strong>{{ $item->name }}</strong><div class="small text-muted">{{ $item->designation }}</div></div></div></td><td>{{ $item->organization ?: '—' }}</td><td>{{ $item->display_order }}@if($item->is_featured)<span class="badge text-bg-warning ms-1">Featured</span>@endif</td><td>{{ $item->published_at?->format('d M Y') ?: 'Draft' }}</td><td><span class="badge {{ $item->is_active ? 'text-bg-success' : 'text-bg-secondary' }}">{{ $item->is_active ? 'Active' : 'Inactive' }}</span></td><td class="text-end"><a class="btn btn-sm btn-outline-primary-brand" href="{{ route('admin.partner-messages.edit', $item) }}">Edit</a><form class="d-inline" method="POST" action="{{ route('admin.partner-messages.destroy', $item) }}" onsubmit="return confirm('Delete this partner message? Uploaded media will be retained safely.')">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form></td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-5">No partner messages have been added yet. <a href="{{ route('admin.partner-messages.create') }}">Add Partner Message</a></td></tr>@endforelse</tbody></table></div></div><div class="card-footer bg-white">{{ $items->links() }}</div>
</div>
@endsection
